name: Upload lens

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  upload-lens:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/lenses-upload.yaml@main
    secrets:
      FHIR_SERVER_URL: ${{ secrets.FHIR_SERVER_URL }}
      DELETE_LENS_URL: ${{ secrets.DELETE_LENS_URL }}
